### ISSUE TITLE
Setting MAC address

### ISSUE THREAD

**Issue by nikhil-robinson** [cyber-murmel/rtltool#1]
How to use rtltool to set the bluethoth mac address of rtl8762c

**Comment by cyber-murmel** [comment]
rtltool itself doesn't provide an option to set the MAC address.

The MAC address is part of the oem config (system config).
One way to change the MAC address, is modify the OEM config file before writing, or to read the oem config of a device, change the address, and write it back.

In my gcc examples, the MAC address is set in the the oem config [source file](https://github.com/cyber-murmel/rtl8762c-gcc-examples/blob/main/config/oem_config.c#L6).
